In [9]:
import os
import csv
import pandas as pd

In [13]:
csvpath = os.path.join('WildLifeTrade2016-2017.csv')
wtrade_df = pd.read_csv(csvpath)
wtrade_df.head(10)

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,2016,I,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,TR,NL,CZ,NaN,1.0,bodies,NaN,T,C
1,2016,I,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
2,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,feathers,NaN,S,W
3,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,specimens,NaN,S,W
4,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,DK,IS,NaN,700.0,NaN,specimens,NaN,S,W
5,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
6,2016,I,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,12.0,feathers,NaN,S,C
7,2016,I,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,4.0,feathers,NaN,S,U
8,2016,I,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,2.0,feathers,NaN,S,W
9,2016,I,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,CH,DE,NaN,NaN,4.0,live,NaN,T,C